#!/bin/bash
# Give wofi list of all unicode characters to copy.
# Shows the selected character in dunst if running.

# Must have wl-copy installed to even show menu.
wl-copy -h >/dev/null 2>&1 || exit

emojifile="emojis.txt"

chosen=$(grep -v "#" $emojifile | wofi --dmenu -i -L 20)

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | wl-copy
notify-send "'$c' copied to clipboard." &

s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
echo "$s" | tr -d '\n' | wl-copy -p
notify-send "'$s' copied to primary." &
